### ISSUE TITLE
QUICKVALUES-graylog_dashboard_widget

### ISSUE THREAD

**Issue by Luubosi** [suzuki-shunsuke/go-graylog#157] opened 2019-08-30 20:05 UTC
Hi,
please could you check graylog_dashboard_widget - QUICKVALUES
whet is show_pie_chart = false , the pie chart is configured as false but in dashboard is pie chart.
I would like to see only data table.
thanks

resource "graylog_dashboard_widget" "dashboard" {
  description = "Level - ${lower(var.environment)}-${lower(var.application)}"
  dashboard_id = "${graylog_dashboard.dashboard.id}"
  type = "QUICKVALUES"
  quick_values_configuration {
    timerange {
      type = "relative"
      range = 604800
    }
    stream_id = "${graylog_stream.stream.id}"
    query = "application:${lower(var.environment)}-${lower(var.application)}"
    field = "level"
    **show_data_table = true
    show_pie_chart = false**
    limit = 10
    sort_order = "desc"
    stacked_fields = ""
    data_table_limit = 50
  }
  cache_time = 10
}

**Comment by suzuki-shunsuke** [comment] 2019-08-31 05:09
Thank you for your feedback!
I found that the root cause is the `omitempty` option of the bool type field.

https://github.com/suzuki-shunsuke/go-graylog/blob/v7.0.0/dashboard_widget.go#L47

I will remove the `omitempty` and resolve this issue.

**Comment by suzuki-shunsuke** [comment] 2019-08-31 06:31
I have created the PR #158

**Comment by suzuki-shunsuke** [comment] 2019-08-31 07:16
I have released the new version [v7.0.1](https://github.com/suzuki-shunsuke/go-graylog/releases/tag/v7.0.1) .
Please check.

**Comment by suzuki-shunsuke** [comment] 2019-08-31 22:33
I close this issue.
https://github.com/suzuki-shunsuke/go-graylog/pull/158#issuecomment-526864979

**Closed by suzuki-shunsuke** 2019-08-31 22:33 UTC
Labels: bug
